# Based on: https://hub.docker.com/_/mongo/
version: '3'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  app:
    build: .
    volumes:
      - ./:/app
